window.regional_summaries = [
    {
        "eventtitle": "Visit Bacchus Marsh",
        "paratext": "There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in Bacchus Marsh.",
        "paratext_html": "<h4>Visit Bacchus Marsh</h4> \r\n<p>There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-bacchus-marsh.html\" target=\"_blank\">Bacchus Marsh</a></b>.<p><br>\r\n<center>\r\n<figure>\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjXKdIpzm55CyhiaYKvh2Hw-EaGrBmIf1kPf5XU4o867kGP7q6PUiVUu6lB_p8IMl_J_oIbs7vtmwEcQCts2uQaaVo6BR-ZRPTrq8O-5V4UZ30NZ0_xlaw8UkuNslPYWGr-O8Waovh3N1YjIdCkWKLEkiiBy8TQ_WdkuvYc-Q3UzLrGSXmeeGXZa5p1p2M/w400/bacchus-marsh-west-melbourne-and-beyond-01.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Bacchus Marsh\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjXKdIpzm55CyhiaYKvh2Hw-EaGrBmIf1kPf5XU4o867kGP7q6PUiVUu6lB_p8IMl_J_oIbs7vtmwEcQCts2uQaaVo6BR-ZRPTrq8O-5V4UZ30NZ0_xlaw8UkuNslPYWGr-O8Waovh3N1YjIdCkWKLEkiiBy8TQ_WdkuvYc-Q3UzLrGSXmeeGXZa5p1p2M/w1200/bacchus-marsh-west-melbourne-and-beyond-01.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-bacchus-marsh.html\">More Information on Bacchus Marsh</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjXKdIpzm55CyhiaYKvh2Hw-EaGrBmIf1kPf5XU4o867kGP7q6PUiVUu6lB_p8IMl_J_oIbs7vtmwEcQCts2uQaaVo6BR-ZRPTrq8O-5V4UZ30NZ0_xlaw8UkuNslPYWGr-O8Waovh3N1YjIdCkWKLEkiiBy8TQ_WdkuvYc-Q3UzLrGSXmeeGXZa5p1p2M/s1600/bacchus-marsh-west-melbourne-and-beyond-01.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Bacchus Marsh",
        "region": "Bacchus Marsh",
        "sortorder": 11,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-bacchus-marsh.html"
    },
    {
        "eventtitle": "Visit Ballarat",
        "paratext": "There are plenty of reasons to keep exploring the Western Victoria. Check out our guide on the great things to do in Ballarat.",
        "paratext_html": "<h4>Visit Ballarat</h4>\r\n<p>There are plenty of reasons to keep exploring the Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/top-5-things-to-do-in-ballarat.html\" target=\"_blank\">Ballarat</a></b>.<p><br>\r\n<center>\r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/top-5-things-to-do-in-ballarat.html\" target=\"_blank\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSL75hm_6HvfvsqXocm6rj7sNN0uJbh6HClUf711lN3q0GMhhnpji9mtL6x20a8QHySArvFltFt44AeCaO-B1qVWAVuH9JT6dGNgaFKK0vC2Dl5cgnt7STHQXRMtMufVdwjdlzWQ0Z8uVmKTOCS0MYMRHeA3VXIcLk63LmnG82sKdRvvWcsCaToaLbehg/w400/Ballarat%20International%20Foto%20Biennale%20-%2010%20-%202023-08-26-%23%23%23.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Ballarat\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSL75hm_6HvfvsqXocm6rj7sNN0uJbh6HClUf711lN3q0GMhhnpji9mtL6x20a8QHySArvFltFt44AeCaO-B1qVWAVuH9JT6dGNgaFKK0vC2Dl5cgnt7STHQXRMtMufVdwjdlzWQ0Z8uVmKTOCS0MYMRHeA3VXIcLk63LmnG82sKdRvvWcsCaToaLbehg/w1200/Ballarat%20International%20Foto%20Biennale%20-%2010%20-%202023-08-26-%23%23%23.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br> \r\n\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/top-5-things-to-do-in-ballarat.html\">More Information on Ballarat</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSL75hm_6HvfvsqXocm6rj7sNN0uJbh6HClUf711lN3q0GMhhnpji9mtL6x20a8QHySArvFltFt44AeCaO-B1qVWAVuH9JT6dGNgaFKK0vC2Dl5cgnt7STHQXRMtMufVdwjdlzWQ0Z8uVmKTOCS0MYMRHeA3VXIcLk63LmnG82sKdRvvWcsCaToaLbehg/s1600/Ballarat%20International%20Foto%20Biennale%20-%2010%20-%202023-08-26-%23%23%23.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Ballarat",
        "region": "Ballarat",
        "sortorder": 9,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/top-5-things-to-do-in-ballarat.html"
    },
    {
        "eventtitle": "Visit Castlemaine",
        "paratext": "Explore country Victoria. Check out our guide on the great things to do in Castlemaine.",
        "paratext_html": "<h4>Explore Castlemaine</h4> \r\n<p>Explore country Victoria and the West. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/castlemaine-attractions.html\" target=\"_blank\">Castlemaine</a></b>.<p><br>\r\n<center>  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/castlemaine-attractions.html\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtYa2tTzJefR11IsJanEJbv7yBJ66An-TqlHEuuWcRohUNw2n8J_IwWT3Y499jxoSXVYULPRn2dW-sgqM_ar5bzWsJNlczGEWHdDlTpEddJJq_wcF_ytFUNJxiwhjvDijMSsYYdPf-dWjgghH0NAPuqz711xMn9QdY_2_NYe2axcsyOA0Uue2G7yDjsIc/w400/Castlemaine---West-Melbourne-and-Beyond---002.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Castlemaine\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtYa2tTzJefR11IsJanEJbv7yBJ66An-TqlHEuuWcRohUNw2n8J_IwWT3Y499jxoSXVYULPRn2dW-sgqM_ar5bzWsJNlczGEWHdDlTpEddJJq_wcF_ytFUNJxiwhjvDijMSsYYdPf-dWjgghH0NAPuqz711xMn9QdY_2_NYe2axcsyOA0Uue2G7yDjsIc/w1200/Castlemaine---West-Melbourne-and-Beyond---002.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>   \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/castlemaine-attractions.html\">More Information on Castlemaine</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtYa2tTzJefR11IsJanEJbv7yBJ66An-TqlHEuuWcRohUNw2n8J_IwWT3Y499jxoSXVYULPRn2dW-sgqM_ar5bzWsJNlczGEWHdDlTpEddJJq_wcF_ytFUNJxiwhjvDijMSsYYdPf-dWjgghH0NAPuqz711xMn9QdY_2_NYe2axcsyOA0Uue2G7yDjsIc/s1600/Castlemaine---West-Melbourne-and-Beyond---002.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Castlemaine",
        "region": "Castlemaine",
        "sortorder": 5,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/castlemaine-attractions.html"
    },
    {
        "eventtitle": "Visit Clunes",
        "paratext": "There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in Clunes.",
        "paratext_html": "<h4>Visit Clunes</h4> \r\n<p>There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-clunes.html\" target=\"_blank\">Clunes</a></b>.<p><br>\r\n<center>\r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-clunes.html\" target=\"_blank\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEigNaK4UorM8nHFyUPjR0UYU2_LLx9MVGN8s4OR5tACpgyKJP_k197lZ8H6lxV1yTF7JJ6wTlWlr84DPYmmmu3RPCZl4VrR-5AeaiVsdfpogpoMTyOiTfrq_nvQOmF7glgXLQC9ZPiNBhL4HqRP_lZe6YnlRS7YvlwDiIROEu_8Idp1PrVknYIpMVhSzIE/w400/Clunes-01.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Clunes\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEigNaK4UorM8nHFyUPjR0UYU2_LLx9MVGN8s4OR5tACpgyKJP_k197lZ8H6lxV1yTF7JJ6wTlWlr84DPYmmmu3RPCZl4VrR-5AeaiVsdfpogpoMTyOiTfrq_nvQOmF7glgXLQC9ZPiNBhL4HqRP_lZe6YnlRS7YvlwDiIROEu_8Idp1PrVknYIpMVhSzIE/w1200/Clunes-01.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-clunes.html\">More Information on Clunes</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEigNaK4UorM8nHFyUPjR0UYU2_LLx9MVGN8s4OR5tACpgyKJP_k197lZ8H6lxV1yTF7JJ6wTlWlr84DPYmmmu3RPCZl4VrR-5AeaiVsdfpogpoMTyOiTfrq_nvQOmF7glgXLQC9ZPiNBhL4HqRP_lZe6YnlRS7YvlwDiIROEu_8Idp1PrVknYIpMVhSzIE/s1600/Clunes-01.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Clunes",
        "region": "Clunes",
        "sortorder": 12,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-clunes.html"
    },
    {
        "eventtitle": "Visit Colac",
        "paratext": "There are plenty of reasons to keep exploring the Western Victoria. Check out our guide on the great things to do in Colac.",
        "paratext_html": "<h4>Visit Colac</h4> \r\n<p>There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/colac-attractions.html\" target=\"_blank\">Colac</a></b>.<p><br>\r\n<center>\r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/colac-attractions.html\" target=\"_blank\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpKjZ1h65GTdNRJKKVC8YqGKOqmRNrLkzZfT4Asn37EfCHjq9pUV-9tgG_mdLRuwTArmjOBvliFt4N534hpfRsTWDqlZhvnGh1JsQGzzced8_yP4W4I_eaGUxLBLeDgWraxoFivX7X914RArE7UWBkcbykpuDWbDA-QKs_qJKS1YKJmS2apgykXr7KxGs/w400/Colac-Summary,-West-Melbourne-and-Beyond.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Colac\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpKjZ1h65GTdNRJKKVC8YqGKOqmRNrLkzZfT4Asn37EfCHjq9pUV-9tgG_mdLRuwTArmjOBvliFt4N534hpfRsTWDqlZhvnGh1JsQGzzced8_yP4W4I_eaGUxLBLeDgWraxoFivX7X914RArE7UWBkcbykpuDWbDA-QKs_qJKS1YKJmS2apgykXr7KxGs/w1200/Colac-Summary,-West-Melbourne-and-Beyond.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/colac-attractions.html\">More Information on Colac</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpKjZ1h65GTdNRJKKVC8YqGKOqmRNrLkzZfT4Asn37EfCHjq9pUV-9tgG_mdLRuwTArmjOBvliFt4N534hpfRsTWDqlZhvnGh1JsQGzzced8_yP4W4I_eaGUxLBLeDgWraxoFivX7X914RArE7UWBkcbykpuDWbDA-QKs_qJKS1YKJmS2apgykXr7KxGs/s1600/Colac-Summary,-West-Melbourne-and-Beyond.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Colac",
        "region": "Colac",
        "sortorder": 8,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/colac-attractions.html"
    },
    {
        "eventtitle": "Visit Creswick",
        "paratext": "Explore more of the West. Check out our guide on the great things to do in Creswick.",
        "paratext_html": "<h4>Explore Creswick</h4> \r\n<p>Explore country Victoria and the West. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/creswick-attractions.html\" target=\"_blank\">Creswick</a></b>.<p><br>\r\n<center>  \r\n<figure>\r\n    <a href=\"https://www.westmelbourneandbeyond.com/p/creswick-attractions.html\">\r\n    <img src='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYaVuDOgQZ9pLOBXqYwya7aK_ZgL6ddr-FoMqfoMIhJAJ9m7ijo2IXmoNRLQFWr12DiKBQrF2_rtYNlsz0agn356uX0PAYWCq1WDClBS7qHsQtTx41ayfxRUDKusWr-f1A35fdTZcJfUut78qcqPhZqUIcaGRQ_VrXrIxBX1xG8xbSUEIx8ckbxzl2cgw/s1600/Creswick-Summary---West-Melbourne-And-Beyond.jpg' alt='Creswick' href='https://www.westmelbourneandbeyond.com/p/creswick-attractions.html' /></a>\r\n    <figcaption><small><em>Image: West Melbourne and Beyond</em></small></figcaption>\r\n</figure>\r\n</center>\r\n<br>   \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/creswick-attractions.html\">More Information on Creswick</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYaVuDOgQZ9pLOBXqYwya7aK_ZgL6ddr-FoMqfoMIhJAJ9m7ijo2IXmoNRLQFWr12DiKBQrF2_rtYNlsz0agn356uX0PAYWCq1WDClBS7qHsQtTx41ayfxRUDKusWr-f1A35fdTZcJfUut78qcqPhZqUIcaGRQ_VrXrIxBX1xG8xbSUEIx8ckbxzl2cgw/s1600/Creswick-Summary---West-Melbourne-And-Beyond.jpg",
        "imgcaption": "Image: West Melbourne And Beyond.",
        "buttontext": "More Information on Creswick",
        "region": "Creswick",
        "sortorder": 13,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/creswick-attractions.html"
    },
    {
        "eventtitle": "Visit Daylesford",
        "paratext": "Keep exploring country Victoria. Check out our guide on the great things to do in Daylesford.",
        "paratext_html": "<h4>Visit Daylesford</h4> \r\n<p>Explore more of Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/daylesford-top-5.html\" target=\"_blank\">Daylesford</a></b>.<p><br> \r\n<center>  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/daylesford-top-5.html\" target=\"_blank\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi845wSLHjUmfPH9YVBmr3FkuM3tXfpRIdBW6tY2zF6M1y2ZzUluczHSyUeMcCZcA8VSPxkjHf4pRQYMGRysynecOschMAJq-yF5KKlmISegff9WSlDc5eAIvn-1ekqGzdWwTd54DWf55SMaFqKJC8FjBM9z9u6z_JPv6l3fpo7jtNQDv3ed9fM7spr_9Q/w400/og-Daylesford-01c.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Daylesford top places to visit\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi845wSLHjUmfPH9YVBmr3FkuM3tXfpRIdBW6tY2zF6M1y2ZzUluczHSyUeMcCZcA8VSPxkjHf4pRQYMGRysynecOschMAJq-yF5KKlmISegff9WSlDc5eAIvn-1ekqGzdWwTd54DWf55SMaFqKJC8FjBM9z9u6z_JPv6l3fpo7jtNQDv3ed9fM7spr_9Q/w1200/og-Daylesford-01c.jpg\"\r\n      style=\"width: auto;\" />\r\n    </picture></a>\r\n\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>   \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/daylesford-top-5.html\">More Information on Daylesford</a></p>\r\n<br> ",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi845wSLHjUmfPH9YVBmr3FkuM3tXfpRIdBW6tY2zF6M1y2ZzUluczHSyUeMcCZcA8VSPxkjHf4pRQYMGRysynecOschMAJq-yF5KKlmISegff9WSlDc5eAIvn-1ekqGzdWwTd54DWf55SMaFqKJC8FjBM9z9u6z_JPv6l3fpo7jtNQDv3ed9fM7spr_9Q/s1600/og-Daylesford-01c.jpg",
        "imgcaption": "Image: West Melbourne and Beyond",
        "buttontext": "More Information on Daylesford",
        "region": "Daylesford",
        "sortorder": 1,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/daylesford-top-5.html"
    },
    {
        "eventtitle": "Visit Kyneton",
        "paratext": "Plan ahead for your next visit to Central and West Central Victoria. Kyneton is the new hotspot in the west!",
        "paratext_html": "<h4>Visit Kyneton</h4>\r\n<p><b>Kyneton</b> has a number of attractions including many wineries! Plan ahead for your next visit to Central and West Central Victoria.</p><br>\r\n  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/kyneton-tourist-destination-top-5.html\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxOkYRjPc4LKmZDfk61YWyiGdj-SXDJdMV0IRTAr6NxVostiqUvhG4ujBxLNCK3444Flfnn5VGIICqp-gBsiDT2LQTgHtKpWhD_HPtag_dY8dYQExU0Dp4JrXl9a1CJreUDGT0gG7LTewlkEdQ5qHBQz50dAPIvq7eo3ep4fakmTqq6QZgtap8wu9B8Hc/w400/og-06a.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Kyneton\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxOkYRjPc4LKmZDfk61YWyiGdj-SXDJdMV0IRTAr6NxVostiqUvhG4ujBxLNCK3444Flfnn5VGIICqp-gBsiDT2LQTgHtKpWhD_HPtag_dY8dYQExU0Dp4JrXl9a1CJreUDGT0gG7LTewlkEdQ5qHBQz50dAPIvq7eo3ep4fakmTqq6QZgtap8wu9B8Hc/w1200/og-06a.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n<figcaption><small><em>Image: West Melbourne and Beyond. </em></small></figcaption>\r\n</figure>\r\n<br> \r\n  \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/kyneton-tourist-destination-top-5.html\">More Information on Kyneton</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxOkYRjPc4LKmZDfk61YWyiGdj-SXDJdMV0IRTAr6NxVostiqUvhG4ujBxLNCK3444Flfnn5VGIICqp-gBsiDT2LQTgHtKpWhD_HPtag_dY8dYQExU0Dp4JrXl9a1CJreUDGT0gG7LTewlkEdQ5qHBQz50dAPIvq7eo3ep4fakmTqq6QZgtap8wu9B8Hc/s1600/og-06a.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Kyneton",
        "region": "Kyneton",
        "sortorder": 6,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/kyneton-tourist-destination-top-5.html"
    },
    {
        "eventtitle": "Visit Lancefield",
        "paratext": "Explore country Victoria. Check out our guide on the great things to do in Lancefield.",
        "paratext_html": "<h4>Visit Lancefield</h4> \r\n<p>Keep exploring western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-lancefield.html\" target=\"_blank\">Lancefield</a></b>.<p><br>\r\n<center>  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-lancefield.html\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMIHpX2nRqgn6v3fgXrcNDbMxmPW3acODU5oDbDeQHa6calNHV1gvJ8rMSNAITZaVhyphenhyphenOR_0cFaEnFCnhuJFQF-J5kkubFBHyPUAFF0kvr6JoxWaUopxNGpl71TQc6bi9ejxvnegd0BHcSzRE6vN7Csqf-Os9cfw3qvWrq_sK4pKbBTa1_vpFKHrTeg9Vw/w400/Lancefield-1.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Lancefield\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMIHpX2nRqgn6v3fgXrcNDbMxmPW3acODU5oDbDeQHa6calNHV1gvJ8rMSNAITZaVhyphenhyphenOR_0cFaEnFCnhuJFQF-J5kkubFBHyPUAFF0kvr6JoxWaUopxNGpl71TQc6bi9ejxvnegd0BHcSzRE6vN7Csqf-Os9cfw3qvWrq_sK4pKbBTa1_vpFKHrTeg9Vw/w1200/Lancefield-1.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>    \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-lancefield.html\">More Information on Lancefield</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMIHpX2nRqgn6v3fgXrcNDbMxmPW3acODU5oDbDeQHa6calNHV1gvJ8rMSNAITZaVhyphenhyphenOR_0cFaEnFCnhuJFQF-J5kkubFBHyPUAFF0kvr6JoxWaUopxNGpl71TQc6bi9ejxvnegd0BHcSzRE6vN7Csqf-Os9cfw3qvWrq_sK4pKbBTa1_vpFKHrTeg9Vw/s1600/Lancefield-1.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Lancefield",
        "region": "Lancefield",
        "sortorder": 4,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-lancefield.html"
    },
    {
        "eventtitle": "Visit Macedon",
        "paratext": "Explore more of regional Victoria. Check out our guide on the great things to do in Macedon.",
        "paratext_html": "<h4>Visit Macedon</h4> \r\n<p>Explore more of regional Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/macedon-things-to-do.html\" target=\"_blank\">Macedon</a></b>.<p><br> \r\n<center>  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/macedon-things-to-do.html\" target=\"_blank\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhYfu0mg3D14LjgDPCHWiK-H_lW6MXDkeeKmFGXkFn4V8W0_P1Tza3JE5Xxbq6vqA7tgAf0BbfHZe06zsylwoHuvXsGtk1ftr6NtTGT74CAGk5EZYdvhuSvQaNV8Js0Cn_ISHITAJjo_9u7OXq6ph6mNYU8ndJzu3dh_F9pDtKbxrUmavPQg0yRP90kHr0/w400/og---Macedon---West-Melbourne-and-beyond---11a.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Macedon\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhYfu0mg3D14LjgDPCHWiK-H_lW6MXDkeeKmFGXkFn4V8W0_P1Tza3JE5Xxbq6vqA7tgAf0BbfHZe06zsylwoHuvXsGtk1ftr6NtTGT74CAGk5EZYdvhuSvQaNV8Js0Cn_ISHITAJjo_9u7OXq6ph6mNYU8ndJzu3dh_F9pDtKbxrUmavPQg0yRP90kHr0/w1200/og---Macedon---West-Melbourne-and-beyond---11a.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture></a>\r\n\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>   \r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/macedon-things-to-do.html\">More Information on Macedon</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhYfu0mg3D14LjgDPCHWiK-H_lW6MXDkeeKmFGXkFn4V8W0_P1Tza3JE5Xxbq6vqA7tgAf0BbfHZe06zsylwoHuvXsGtk1ftr6NtTGT74CAGk5EZYdvhuSvQaNV8Js0Cn_ISHITAJjo_9u7OXq6ph6mNYU8ndJzu3dh_F9pDtKbxrUmavPQg0yRP90kHr0/s1600/og---Macedon---West-Melbourne-and-beyond---11a.jpg",
        "imgcaption": "Image: West Melbourne and Beyond",
        "buttontext": "More Information on Macedon",
        "region": "Macedon",
        "sortorder": 2,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/macedon-things-to-do.html"
    },
    {
        "eventtitle": "Visit Malmsbury",
        "paratext": "There are plenty of reasons to keep exploring the country Western Victoria. Check out our guide on the great things to do in Malmsbury.",
        "paratext_html": "<h4>Explore more of Victoria - Malmsbury</h4> \r\n<p>There are plenty of reasons to keep exploring Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-malmsbury.html\" target=\"_blank\">Malmsbury</a></b>.<p><br>\r\n  \r\n<center>  \r\n<figure>\r\n  <a href =\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-malmsbury.html\"> \r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgRqGz3yy4364TsZ5kbTSQsZka9nXlwWGVG9Y-eTIvql9vmI9oi-BCW15MXfsC63wx9IgEfdYCHblr6gOURLVnzzGGrdE8p3-mn3yi2Xxu8y3SGn8rElN673ND_3F6-MTJf_H8pbYJ9DIiWw3zM_kS_o7UcozQcoBGr8LThRBiQlMmLFVAocLdqTta4RMk/w400/Malmsbury-02.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Malmsbury\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgRqGz3yy4364TsZ5kbTSQsZka9nXlwWGVG9Y-eTIvql9vmI9oi-BCW15MXfsC63wx9IgEfdYCHblr6gOURLVnzzGGrdE8p3-mn3yi2Xxu8y3SGn8rElN673ND_3F6-MTJf_H8pbYJ9DIiWw3zM_kS_o7UcozQcoBGr8LThRBiQlMmLFVAocLdqTta4RMk/w1200/Malmsbury-02.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>Image: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-malmsbury.html\">More Information on Malmsbury</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgRqGz3yy4364TsZ5kbTSQsZka9nXlwWGVG9Y-eTIvql9vmI9oi-BCW15MXfsC63wx9IgEfdYCHblr6gOURLVnzzGGrdE8p3-mn3yi2Xxu8y3SGn8rElN673ND_3F6-MTJf_H8pbYJ9DIiWw3zM_kS_o7UcozQcoBGr8LThRBiQlMmLFVAocLdqTta4RMk/s1600/Malmsbury-02.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Malmsbury",
        "region": "Malmsbury",
        "sortorder": 7,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/top-things-to-do-in-malmsbury.html"
    },
    {
        "eventtitle": "Visit Taradale",
        "paratext": "There are plenty of reasons to keep exploring country Victoria. Check out our guide on the great things to do in Taradale.",
        "paratext_html": "<h4>Visit Taradale</h4> \r\n<p>There are plenty of reasons to keep exploring country Western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/taradale-things-to-do.html\" target=\"_blank\">Taradale</a></b>.<p><br>\r\n<center>\r\n<figure>\r\n  <a href =\"https://www.westmelbourneandbeyond.com/p/taradale-things-to-do.html\">  \r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirWRY_9trd6b6fl8vPmiNhh8krk4C0MuzwgCT-jvbMuJMlHYwb6uYdbDa1zMtc4IRWFOcMc_X1tz4VMM_2gWDn7GMwZMo2jDKCEMUJtM3iwaG0f2uvufz9tkKMMD8nKJkl-wl6tmL5ooMZPcWajkUiTYsYki_ByyQugWgK2t7ZNWsCKZzGQnJG8Ml7874/w400/og-Taradale-01.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Taradale\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirWRY_9trd6b6fl8vPmiNhh8krk4C0MuzwgCT-jvbMuJMlHYwb6uYdbDa1zMtc4IRWFOcMc_X1tz4VMM_2gWDn7GMwZMo2jDKCEMUJtM3iwaG0f2uvufz9tkKMMD8nKJkl-wl6tmL5ooMZPcWajkUiTYsYki_ByyQugWgK2t7ZNWsCKZzGQnJG8Ml7874/w1200/og-Taradale-01.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture>\r\n  </a>\r\n  <figcaption>\r\n    <small><em>mage: West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/taradale-things-to-do.html\">More Information on Taradale</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirWRY_9trd6b6fl8vPmiNhh8krk4C0MuzwgCT-jvbMuJMlHYwb6uYdbDa1zMtc4IRWFOcMc_X1tz4VMM_2gWDn7GMwZMo2jDKCEMUJtM3iwaG0f2uvufz9tkKMMD8nKJkl-wl6tmL5ooMZPcWajkUiTYsYki_ByyQugWgK2t7ZNWsCKZzGQnJG8Ml7874/s1600/og-Taradale-01.jpg",
        "imgcaption": "Image: West Melbourne and Beyond",
        "buttontext": "More Information on Taradale",
        "region": "Taradale",
        "sortorder": 10,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/taradale-things-to-do.html"
    },
    {
        "eventtitle": "Visit Trentham",
        "paratext": "Keep exploring country Victoria. Check out our guide on the great things to do in Trentham.",
        "paratext_html": "<h4>Visit Trentham</h4> \r\n<p>Keep exploring western Victoria. Check out our guide on the great things to do in <b><a href=\"https://www.westmelbourneandbeyond.com/p/trentham-attractions.html\" target=\"_blank\">Trentham</a></b>.<p><br>\r\n<center>  \r\n<figure>\r\n  <a href=\"https://www.westmelbourneandbeyond.com/p/trentham-attractions.html\">\r\n  <picture>\r\n    <!-- Mobile (up to 768px) -->\r\n    <source \r\n      media=\"(max-width: 768px)\" \r\n      srcset=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiASzZlGD2zGkQZzkf2DCFPsHZfHNkk4xhCBWpeUg4oUX522wU_LCoy73YmUE_SkxFLctvvU9NKXVTF22-gM4P_Kc8-AwaB7xI6bA66R-gne2IeaE678iGjEq9Wwr4-y0s3n6j2amiM4OmgaY1xyUvbWZTr3uiaJ0tV0XzHND1eaksrSGTK-lF2FUClAyc/w400/og---Trentham---West-Melbourne-And-Beyond.jpg\">\r\n\r\n    <!-- Default (desktop) -->\r\n    <img \r\n      loading=\"lazy\" \r\n      decoding=\"async\"\r\n      alt=\"Top things to do in Trentham\"\r\n      src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiASzZlGD2zGkQZzkf2DCFPsHZfHNkk4xhCBWpeUg4oUX522wU_LCoy73YmUE_SkxFLctvvU9NKXVTF22-gM4P_Kc8-AwaB7xI6bA66R-gne2IeaE678iGjEq9Wwr4-y0s3n6j2amiM4OmgaY1xyUvbWZTr3uiaJ0tV0XzHND1eaksrSGTK-lF2FUClAyc/w1200/og---Trentham---West-Melbourne-And-Beyond.jpg\"\r\n      style=\"width: auto;\" />\r\n  </picture></a>\r\n\r\n  <figcaption>\r\n    <small><em>West Melbourne and Beyond.</em></small>\r\n  </figcaption>\r\n</figure>\r\n</center>\r\n<br>\r\n<!--Click Link-->\r\n<p><a class=\"one blinkImg\" href=\"https://www.westmelbourneandbeyond.com/p/trentham-attractions.html\">More Information on Trentham</a></p>\r\n<br>",
        "imgurl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiASzZlGD2zGkQZzkf2DCFPsHZfHNkk4xhCBWpeUg4oUX522wU_LCoy73YmUE_SkxFLctvvU9NKXVTF22-gM4P_Kc8-AwaB7xI6bA66R-gne2IeaE678iGjEq9Wwr4-y0s3n6j2amiM4OmgaY1xyUvbWZTr3uiaJ0tV0XzHND1eaksrSGTK-lF2FUClAyc/s1600/og---Trentham---West-Melbourne-And-Beyond.jpg",
        "imgcaption": "Image: West Melbourne And Beyond",
        "buttontext": "More Information on Trentham",
        "region": "Trentham",
        "sortorder": 3,
        "pageurl": "https://www.westmelbourneandbeyond.com/p/trentham-attractions.html"
    }
]
